### ISSUE TITLE
¿ Can i center text in #rowspan# ?

### ISSUE THREAD

**Issue by Blizk** [TobiasBg/TablePress#111]
Im using TablePress for my website i want to know if is posible to center my text only when i use the #Rowsapn#

**Comment by TobiasBg** [comment]
Hi @Blizk,
thanks for your post, and sorry for the trouble.

Yes, this is possible, but we will need some adjusted CSS selectors. Can you please post a link to the page with the table where this problem happens, so that I can take a direct look? Thanks!

Regards,
Tobias

**Comment by Blizk** [comment]
http://pinmedinstruments.com/product/esponja-de-gasa/ 

If you see the Table i use #rowspan# for combine some cells but i want to be centered. 
Sorry if you dont understand me my englich is not good. 

i also speak French and Spanich.

**Comment by TobiasBg** [comment]
Hi @Blizk,

thanks! For that, just add this to the "Custom CSS" textarea on the "Plugin Options" screen of TablePress:
```CSS
.tablepress-id-68 tbody td,
.tablepress-id-68 thead th {
  text-align: center;
  vertical-align: middle;
}
```
Regards,
Tobias
